### ISSUE TITLE
Row Count Validation

### ISSUE THREAD

**Issue by leejaykar** [unchartedsoftware/PLUTO#145]
As an MVP, having the option to compare a previous version of a dataset the amount of rows in a subsequent data load might be handy for some data. I'm thinking anything related to something like administrative areas where the number of states, provinces, territories, etc should remain constant. 

Future development will entail being able to allow partial files to load.

**Comment by lcorrigall** [comment]
need:
Min and max thresholds to generate both errors and warnings
