### ISSUE TITLE
general config and rules - can set negative values

### ISSUE THREAD

**Issue by Maunique** [unchartedsoftware/PLUTO#216]
Edit Ruleset and rules

Can set negative values for:
General Config
How many dropped items as a percentage of the total before aborting?
How many total dropped items before aborting?
How many total warnings before aborting?

Rules
How many dropped items before aborting on this rule?
How many warnings before aborting on this rule?
Minimum Number of Data Rows Otherwise Warning
Maximum Number of Data Rows Otherwise Warning 
Minimum Number of Data Rows Otherwise Error
Maximum Number of Data Rows Otherwise Error

**Comment by lcorrigall** [comment]
Need to add UI validation to the rule properties
