### ISSUE TITLE
Please add client side validations for filenames

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#228]
There are limitations to the filename that can be processed by MAPS backend at this time.  Therefore we'd like to add the following client side validations to the filename entered by clients:

1.  Only allow files with the extensions ".csv", ".geojson", ".zip".  Please note this list may expand overtime so please be sure this is easily extended.  
2. Only allow filenames that are 35 characters long (without counting the extension)
3. Verify the filename only has alphanumeric characters and/or '_'

**Comment by ptokarchuk-uncharted** [comment]
We'll do this by extending our UI definitions to include a list of regexes that can be used to validate input.
