### ISSUE TITLE
Add new file to load Popup

### ISSUE THREAD

**Issue by leejaykar** [unchartedsoftware/PLUTO#339]
Change "File path" to "File Name"

If possible, create a separate text-box to enter subfolder. If so, mark as: "BCOS Bucket Sub-Folder (Optional)"

**Comment by lcorrigall** [comment]
That field is part of the custom BCOS Importer and Exporter.  Easy to change, but part of your custom build.

**Comment by bb-acarrera** [comment]
Closing.  A new ticket was created on our GitHub for our repository holding our custom plugins.
