### ISSUE TITLE
Allow pass-through with no validation

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#365]
Currently pluto will perform parsing and validation on CSV files.  However while we iterate and add support for validation of other formats we would like pluto to continue to process other types of data files (ie: geojson, geojson.gz, shp files, etc.).  In order to allow these files in the user needs to select "CSV Parser" and a validation.

Until we add validation for these types could we potentially add an option that makes it more explicit pluto doesn't need to parse the file and let it pass through?  As a precaution we could also make it clear to the user that there is no validation and they assume the risks of letting it pass through.

**Comment by lcorrigall** [comment]
Will be in 0.9.5
