### ISSUE TITLE
Validation does not register dropped row

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#378]
Pluto version 0.9.4

1) Send in a csv file with only two rows (header row, data row).  The csv should fail the validation setup in the UI.
2) process the file
   -> The UI will not show a row as dropped (and therefore pass validation even if abort on 1 dropped row is set).  However the output file correctly has the dropped row.  

It is believed (without digging through code yet) this error triggers if the validation rule does not set a reason for the dropped row.  However this needs to be confirmed.

**Comment by bb-acarrera** [comment]
It was confirmed that adding a reason for the dropped row appears to fix this issue.

**Comment by lcorrigall** [comment]
Was issue with the rules -- rules need to indicate that rows were dropped.
