### ISSUE TITLE
Please update Validation Setup UI to be consistent on "Tests"

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#386]
Pluto ver 0.9.4

If a user updates the parameters of a "Rule" in the "Validation Setup" UI the "Test", "Test from local file", and "Upload" buttons will be marked insensitive and users will be notified to save changes prior to using these features.

However if I add a new rule (do not change parameters) or delete a rule the same buttons do not become insensitive.  They will process the last saved ruleset which can be misleading to the user.

**Comment by lcorrigall** [comment]
This has been fixed in 0.9.5 -- see #359
