### ISSUE TITLE
Pluto crashes under heavy load

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#388]
pluto ver 0.9.4

Machine - 2 CPU, 4 GB Memory
Docker container limit to 1.5 CPU and 1GB Memory

Steps to reproduce:
1) Using load test script (flags -n 200 -s 8) for two different rulesets simultaneously
   -> Server will eventually crash with following message

/opt/PLUTO/server/routes/processFile.js:276
                console.log('child process exited with code ' + code.toString());
                                                                     ^

TypeError: Cannot read property 'toString' of null
    at ChildProcess.proc.on (/opt/PLUTO/server/routes/processFile.js:276:70)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by lcorrigall** [comment]
Fixed on 0.9.5 (as part of the graceful server shutdown), this specific fix has be hotfixed onto 0.9.4 under branch v0.9.4-1, tagged at 0.9.4-1

**Comment by bb-acarrera** [comment]
Confirmed this no longer occurs in pluto ver 0.9.4-1
