### ISSUE TITLE
Continue button dropdown does not become insensitive when the continue button is

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#409]
Pluto version 0.9.5-1 and 0.9.6

Steps to reproduce
1) Click "Edit Validation Setups"
2) Click "Clone" on any ruleset
   -> The continue button is insensitive, but the drop down arrow is not.  The options in the drop down are correctly insensitive which is good.  However should the user be able to open the drop down at all while the button (and all dropdown items) are insensitive?

**Comment by NullMad** [comment]
https://github.com/unchartedsoftware/PLUTO/pull/429
