### ISSUE TITLE
Linked upload locations do not propagate properly

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#414]
Pluto version 0.9.6

Steps to reproduce
1) Create and save a validation with a separate (non-linked) download and upload location
2) Create a new upload location and link it to the download location choose in step 1
3) Open the validation created in step 1
    -> The UI will correctly not display the upload location now that the download location has a linked upload location.
4) Click "Upload"
    -> It will use the upload location set in step 1, not the newly linked upload location.   The user is required to re-select the download location in order for it to take effect.

**Comment by lcorrigall** [comment]
In 0.9.7
