### ISSUE TITLE
Invalid row number incorrect on validation

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#424]
Pluto versions 0.9.4-1, 0.9.5-1, 0.9.6

If a validation fails for a particular row the row number in the "File Load Status" notifications is incorrect.

For example:

1) Create a validation for a file with "Check Column Count"
2) Upload a bad file with just a header row and 1 row with too many columns
3) Test the validation
    -> It'll return row "222" has too many columns.

**Comment by lcorrigall** [comment]
Fixed, but in a roundabout way.  The csv parser adds a column to track the original row index at the beginning of parsing, but if there is an inconsistent number of rows that value was placed in the wrong column.  Now, the parser will throw and error if there is an inconsistent number of columns across rows.
