### ISSUE TITLE
Please include console errors when process throws uncaught exception

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#425]
Pluto ver 0.9.6

The plugins (exporter/importer) purposefully do not catch their exceptions because the pluto_server itself catches them and reports errors to the user.  However in this event the user will only see the following on the UI: "Error | ProcessFileRouter | Run stopped without cleaning up. Server has marked this as finished.".  However it'll be more useful to see the actual exception trace on the UI as well.  Otherwise users will need to redirect to kibana and/or the docker logs to determine what the actual error is.

**Comment by lcorrigall** [comment]
Hmmm, yes.  That kind of error should only occur if the validation process crashes (which is not supposed to happen) or if the container is killed without getting a chance to close down.  Which importer or exporter are you seeing this?

**Comment by bb-acarrera** [comment]
The new cartoExporter which was derived off the BCOSExporter

**Comment by lcorrigall** [comment]
Moving this over to #389
