### ISSUE TITLE
Validation Setups filter does not work as expected

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#430]
Pluto version 0.9.6

1) There are multiple temp_avg.... files in the validation setups grid as seen by the "temp_" filter.
![screen shot 2018-03-14 at 8 16 16 am](https://user-images.githubusercontent.com/27735868/37401968-3cd7e0ee-2760-11e8-9ca7-97e5c5f673f7.png)

2) However if you continue the filter with temp_a the grid becomes blank when I would have expected three rows to remain.
![screen shot 2018-03-14 at 8 16 26 am](https://user-images.githubusercontent.com/27735868/37401932-1d31b666-2760-11e8-8b80-cbb1b7c90f43.png)

**Comment by lcorrigall** [comment]
in1.0.9
