### ISSUE TITLE
Allow groups for customValidationFields

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#446]
Users can add additional input fields for metadata as "customValidationFields" in validatorConfig.json.  Every field appears as an additional entry under "Additional Information" in the ruleset UI.  If there are many fields configured this can appear cluttered/confusing to the user.  Please add the ability to "group" fields together under a customizable header for easier readability.  

For example:

Instead of 
- source
- link
- data contact
- engineering contact

Users can have it appear as
- General Information 
    - source
    - link
- Contact Information
    - data contact
    - engineering contact

**Comment by lcorrigall** [comment]
in 1.0.9
