### ISSUE TITLE
maxConcurrentTasks off by 1

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#471]
pluto ver 1.0.7

The following line was added to validatorConfig.json:

"maxConcurrentTasks": 10,

However when sending 20 requests (same file without MD5 check) in a tight loop the server happily took then and 20 startValidator.js processes can be seen running in the container.  The server should have rejected the last 10 requests.

**Comment by bb-acarrera** [comment]
The config does take effect with pluto ver 1.0.7-1.  However it appears there is an off by one error.  If I set maxConcurrentTasks to 10 it allows 11 in before it starts returning errors.

**Comment by lcorrigall** [comment]
In 1.09
