### ISSUE TITLE
Error uploading file after md5 check

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#550]
Pluto version 1.0.10

Steps to reproduce:
1) Open the validation of a file that has not changed (but previously uploaded)
2) Click "Upload"
    -> It should return with the value of "Not validated" since the md5 hasn't changed
3) Click "Upload/Skip duplicate check"
    -> Error popup appears: "Failed to create: You must specify a name or id"

The only way to resolve the issue is to reload the validation UI and click "Upload/Skip duplicate check".

**Comment by bb-acarrera** [comment]
May potentially be related to #549

**Comment by pandersen-uncharted** [comment]
Identical to #549. Closing...
