### ISSUE TITLE
Validation configuration changes do not save after an upload

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#551]
Pluto ver 1.0.10

Steps to reproduce:
1) Open a validation
2) Click "Upload" (doesn't matter if it fails or succeeds)
3) Change a validation rule property
4) Click "Save"
    -> A popup will appear denoting the changes were saved and the UI will reload
    -> Review the property changed in step 3 and it shows the old value.

**Comment by pandersen-uncharted** [comment]
I can't reproduce this and believe it was fixed with the fix to #549.
