### ISSUE TITLE
UI does not properly handle http status code 413

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#552]
Pluto version 1.0.10

Steps to reproduce:
1) Open a validation
2) Click "Test from local file"
    -> Select a file that has unicode characters (ie: Japanese characters)
    -> An error message appears with the cryptic text: "[object Object]" and the "Processing" icon persists indefinitely.

**Comment by pandersen-uncharted** [comment]
The unicode is in the file.
The validation has "Check Column Count” and “Check Column Names”. So they are JavaScript rules which should properly handle unicode.

**Comment by pandersen-uncharted** [comment]
Add "日本アコモデーションファンド投資法人" into a column in a file.

**Comment by pandersen-uncharted** [comment]
Try a ruleset with no rules. And try a file with Japanese characters in the headers.

**Comment by pandersen-uncharted** [comment]
I've tried this with a file with no rules and it works fine for me. I suspect this may be related to #553 where the client gets into a weird state that's causing the Processing icon to persist (and perhaps other things).

**Comment by bb-acarrera** [comment]
This issue replicates in version 1.0.11.  However the symptom of the "Processing" icon persisting affects all validations.  Every validation you open (or new ones created) will have the "Processing" icon appear.  The only resolution is to reload the website.

**Comment by pandersen-uncharted** [comment]
When the client suffers an error like the one described above it gets into a bad state leading to the "Processing" icon appearing at incorrect times.

**Comment by bb-acarrera** [comment]
It appears the issue is not related to the unicode character at all.  It appears that a 413 status code is returned from the nginx server leading to this issue.

**Comment by pandersen-uncharted** [comment]
Okay. I think I now understand what's happening. When the 413 error is returned the code is catching it and throwing up an alert. Unfortunately the code that throws up alerts seems to be expecting a string rather than an error object. So you get the '[object Object]' message. The Processing icon remains because the flag controlling it is not reset when the error is received.

**Comment by pandersen-uncharted** [comment]
Digging deeper the code is properly handling and displaying errors generated by the server. Could nginx be sending back ill-formed errors?

**Comment by pandersen-uncharted** [comment]
The problem seems to be with the response from nginx. Ember doesn't seem to know how to handle responses that include content. If I create an error with the following code
`		let contentMsg = '<html> \
		<head><title>413 Request Entity Too Large</title></head> \
		<body bgcolor="white"> \
		<center><h1>413 Request Entity Too Large</h1></center> \
		<hr><center>nginx/1.9.6</center> \
		</body> \
		</html> \
		 \
		 \
		 \
		 \
		 \
		';

		res.set('Content-Type', 'text/html');
		res.set('Content-Length', contentMsg.length.toString());
		res.statusMessage = 'Request Entity Too Large';
		res.send(contentMsg);
		res.status(413).end();
		return
`
Then I get "SyntaxError: Unexpected token < in JSON at position 0" as the error in Ember.

**Comment by pandersen-uncharted** [comment]
According to this Stackoverflow comment Ember is expecting a JSON response. The fact it gets HTML (or any non-JSON back) would confuse it. https://stackoverflow.com/questions/12968829/how-should-errors-be-handled-when-using-the-ember-js-data-restadapter

**Comment by pandersen-uncharted** [comment]
What happens in client/routes/edit-ruleset.js:model() when an error occurs. Does it have an opportunity to deal with the error?
