### ISSUE TITLE
Processing icon appears on newly added file

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#553]
Pluto ver 1.0.10

Steps to reproduce:
1) Click "Add new file"
2) Fill out the source/destination/parser with any values
3) Once the UI changes to the full "Edit Validation" form scroll to the bottom.  The "Processing..." icon appears.  I assume this is an error, otherwise I'm not sure what is actually processing.

**Comment by pandersen-uncharted** [comment]
I was able to reproduce this. I created a new file uploading and downloading from local given garbage filenames. The processing icon appeared immediately.

**Comment by pandersen-uncharted** [comment]
I tried this a second time and wasn't able to reproduce it. I suspect the problem is something else, that the client gets in a bad state somehow and always shows the processing icon. For example when I first reproduced the problem I went to edit an existing file and the icon appeared there too.

**Comment by pandersen-uncharted** [comment]
As with other bugs I'm starting to suspect that #549 was also responsible for this one.

**Comment by bb-acarrera** [comment]
This issue doesn't replicate for me in ver 1.0.11
