### ISSUE TITLE
Download and Upload configuration properties do not appear on admin page

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#556]
Pluto ver 1.0.11

On the admin page the configuration properties (returned by static get ConfigProperties) do not appear when editing a download or upload configuration.

**Comment by pandersen-uncharted** [comment]
Hidden properties are not being shown but regular ones are (at least in my test). I've reached out to Luke to learn what the design intent for this is. The way the code is currently structured it seems that this would take a bit of work to change. (It seems that hidden properties are weeded out on the client side.) I'll dig deeper in the meantime.

**Comment by bb-acarrera** [comment]
Hidden properties should not be shown in the "Edit Validations" page.  However they should display on the admin page to allow us to update them.

**Comment by pandersen-uncharted** [comment]
Fixed in 1.0.12. On the Admin page if the user is in the correct group or an Admin they see the hidden properties.

**Comment by bb-acarrera** [comment]
In 1.0.12 this is fixed for the "Download Locations".  However the issue still appears in "Upload Locations".

**Comment by pandersen-uncharted** [comment]
For some reason that I can't fathom the client requests the "Upload Locations" UI information twice, in two contexts, one is the Admin context which has the returns the hidden elements and then a second time without them. Why we get two requests is what I'm looking into at the moment.

**Comment by pandersen-uncharted** [comment]
What appears to be happening is that after the data for the request is handled (and the hidden properties are returned) a second request comes in to update the page that's being left which again queries for the data but this time without the properties. So it seems the client must maintain and decide when to show hidden properties. This can't be done on the server unless a separate data model object is introduced so that there can be configured rules with and without hidden properties.

**Comment by pandersen-uncharted** [comment]
Ember keeps a copy of objects and doesn't expect them to be in two states at the same time (properties hidden and not hidden in this case) so depending on the order of how objects are retrieved from the server they might wind up with the hidden properties or not. The old implementation assumed it could query for the objects in isolation but that didn't work. So now the server is always returning objects with the hidden properties (if the user has appropriate admin rights) and leaving it to the client when to or not to show them.
