### ISSUE TITLE
Post Process Task - Allow for absolute path in manifest.json

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#560]
When adding modules to the "posttasks" section of manifest.json the "script" always assumes the path provided is within the customRules directory even if a full path is provided.  Please change this to match the other components (exporters, importers, reporters, rules) and use the full path if provided.  Only add a default base path if a relative path is provided.

**Comment by pandersen-uncharted** [comment]
Could you confirm this doesn't work? The loading of post tasks goes through exactly the same code as the loading of rules, imports, etc. I did try this and had a post task referenced by an absolute path and it was referenced properly.

**Comment by bb-acarrera** [comment]
Weird, this didn't work before.  It could of been fixed by a misconfiguration or the fact that I recently did a clean build.  This doesn't seem to replicate.
