### ISSUE TITLE
Post Process Task - Allow propagation of UI errors

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#562]
In the Carto post process task the "Carto Dataset Link Column" populates via a http call based on the value in the "Carto Dataset" dropdown.  However if the http call fails with a non-200 status code the UI does not give any indication an error has occurred and simply shows the data as loading.  Please allow the error to propagate to the UI to indicate to the user the UI is in a bad state.

**Comment by pandersen-uncharted** [comment]
The code which handles this is in `src/client/app/components/custom-property/choice.js` in the *choices* property. On an error an empty list is returned. I can change this so that the list contains an error string.

**Comment by pandersen-uncharted** [comment]
I'll shortly be returning a partial fix for this. Now when there's an error an error is returned as the list. Unfortunately the user will be able to select the error as if it were a value. This isn't ideal. Unfortunately a better fix will take some time. What I believe should happen is that when an error occurs the `choice` component should be replaced by a static label displaying the error. This however would take some time to implement.
