### ISSUE TITLE
Post Process Task is triggered on Test

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#563]
When testing a dataset it appears the server is also running the post process task.  This may not be correct based on the post process task.  For example the carto post process task will create a new dataset based upon the pluto dataset.  At best case this will fail because the pluto dataset doesn't exist.  At worst case it may actually modify the carto dataset without performing the pluto upload.  

This should either be blocked on test or the user should have the option to specify if it can be triggered on test.

**Comment by pandersen-uncharted** [comment]
For simplicity I changed the code so that post tasks are not run during a test.
