### ISSUE TITLE
Runs - Showing Pg 3 of 2

### ISSUE THREAD

**Issue by Maunique** [unchartedsoftware/PLUTO#90]
pluto runs
1- all options checked
2- go to page 3
3- uncheck Show Warnings

Blank page with Pg 3 of 2 displayed
[Oct16 pg 3 of 2.pdf](https://github.com/unchartedsoftware/PLUTO/files/1387751/Oct16.pg.3.of.2.pdf)

**Comment by lcorrigall** [comment]
Fixed as part of work re-setting page to 1 when filters changed

**Comment by Maunique** [comment]
Fix verified
