### ISSUE TITLE
Runs - not displaying runs after unchecking option

### ISSUE THREAD

**Issue by Maunique** [unchartedsoftware/PLUTO#91]
pluto runs
1- all options checked
2- go to page 2
3- uncheck Show Errors

Expected: Warnings displayed
Actual: nothing displayed
[Oct16 showing blank.pdf](https://github.com/unchartedsoftware/PLUTO/files/1387768/Oct16.showing.blank.pdf)

**Comment by lcorrigall** [comment]
Fixed as part of reset to page 1 on filter change

**Comment by Maunique** [comment]
Fix verified
